spring:
  config:
    activate:
      on-profile: dev
  liquibase:
    contexts: dev

ai:
  behavior:
    processing:
      worker:
        delay-seconds: 120
        max-retries: 1
    retention:
      temp-events-ttl-days: 7
    security:
      rate-limiting:
        enabled: false
